# Generated by Django 3.2.7 on 2021-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
