# Generated by Django 3.2.7 on 2021-09-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='timestamp',
        ),
    ]
