# Generated by Django 3.2.7 on 2021-10-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210928_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='plate',
            field=models.CharField(default='KIA-605', max_length=50),
            preserve_default=False,
        ),
    ]
