# Generated by Django 3.2.7 on 2021-11-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='humidity',
            field=models.CharField(default=85, max_length=50),
            preserve_default=False,
        ),
    ]
